# Generated by Django 5.2.12 on 2026-06-25 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('setup', 'Setup'), ('emotion', 'Emotion')], max_length=20)),
                ('label', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_date', models.DateField(default=django.utils.timezone.localdate)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=120)),
                ('market', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('Compra', 'Compra'), ('Venda', 'Venda')], max_length=10)),
                ('setup', models.CharField(blank=True, max_length=120)),
                ('timeframe', models.CharField(blank=True, default='1M', max_length=40)),
                ('account', models.CharField(blank=True, max_length=120)),
                ('entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('planned_trade', models.BooleanField(default=True)),
                ('market_context', models.TextField(blank=True)),
                ('entry_reason', models.TextField(blank=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('emotion_before', models.CharField(blank=True, max_length=120)),
                ('emotion_during', models.CharField(blank=True, max_length=120)),
                ('emotion_after', models.CharField(blank=True, max_length=120)),
                ('execution_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('mistakes', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('followed_plan', models.BooleanField(default=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('result', models.CharField(blank=True, choices=[('Gain', 'Gain'), ('Loss', 'Loss'), ('Zero', 'Zero')], max_length=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('initial_risk', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('r_multiple', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risk_reward', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
