# Generated by Django 5.2.15 on 2026-06-26 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaloption',
            options={'verbose_name': 'opção do diário', 'verbose_name_plural': 'opções do diário'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': 'trade', 'verbose_name_plural': 'trades'},
        ),
        migrations.AlterField(
            model_name='journaloption',
            name='kind',
            field=models.CharField(choices=[('setup', 'Setup'), ('emotion', 'Emoção')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='journaloption',
            name='label',
            field=models.CharField(max_length=120, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='account',
            field=models.CharField(blank=True, max_length=120, verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venda', 'Venda')], max_length=10, verbose_name='direção'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='duração em minutos'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='emotion_after',
            field=models.CharField(blank=True, max_length=120, verbose_name='emoção depois'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='emotion_before',
            field=models.CharField(blank=True, max_length=120, verbose_name='emoção antes'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='emotion_during',
            field=models.CharField(blank=True, max_length=120, verbose_name='emoção durante'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='preço de entrada'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_reason',
            field=models.TextField(blank=True, verbose_name='motivo da entrada'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de entrada'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='execution_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='nota de execução'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='preço de saída'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_reason',
            field=models.TextField(blank=True, verbose_name='motivo da saída'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de saída'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='taxas'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followed_plan',
            field=models.BooleanField(default=True, verbose_name='seguiu o plano'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='initial_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='risco inicial'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lessons',
            field=models.TextField(blank=True, verbose_name='lições'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.CharField(blank=True, max_length=120, verbose_name='mercado'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market_context',
            field=models.TextField(blank=True, verbose_name='contexto de mercado'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='mistakes',
            field=models.TextField(blank=True, verbose_name='erros'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='planned_trade',
            field=models.BooleanField(default=True, verbose_name='operação planejada'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='pnl'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='r_multiple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='múltiplo de r'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='result',
            field=models.CharField(blank=True, choices=[('Gain', 'Ganho'), ('Loss', 'Perda'), ('Zero', 'Zero')], max_length=10, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='risco/retorno'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='print'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='setup',
            field=models.CharField(blank=True, max_length=120, verbose_name='setup'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='stop loss'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=120, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='alvo'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timeframe',
            field=models.CharField(blank=True, default='1M', max_length=40, verbose_name='timeframe'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='data do trade'),
        ),
    ]
