# Generated by Django 5.2.15 on 2026-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journaloption_options_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_points_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='stop líquido (pontos)'),
        ),
        migrations.AddField(
            model_name='trade',
            name='target_points_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='pontos líquidos (alvo)'),
        ),
    ]
