# Generated by Django 5.2.15 on 2026-07-01 18:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_trade_stop_points_net_trade_target_points_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='point_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=14, verbose_name='valor por ponto (R$)'),
        ),
    ]
