# Generated by Django 5.2.15 on 2026-07-01 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_trade_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fee_per_contract',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.55'), max_digits=14, verbose_name='taxa por contrato (R$)'),
        ),
    ]
